queue_rules:
  - name: default
    merge_method: squash
    batch_size: 1

    queue_conditions:
      - label!=WIP
      - -draft

    merge_conditions:
      - "#approved-reviews-by>=1"
      - check-success=*
      - base=main


pull_request_rules:
  - name: Add approved PRs to merge queue

    conditions:
      - base=main
      - -draft
      - "#approved-reviews-by>=1"
      - check-success=*

    actions:
      queue:
        name: default
