queue_rules:
  - name: default
    merge_method: squash

    queue_conditions:
      - label!=WIP
      - draft=false

    merge_conditions:
      - "#approved-reviews-by>=1"
      - check-success=CI
      - base=main

    batch_size: 1


pull_request_rules:

  - name: Add approved PRs to merge queue
    conditions:
      - base=main
      - draft=false
      - "#approved-reviews-by>=1"
      - check-success=CI

    actions:
      queue:
        name: default